from .boundary_roles import (
    BoundaryClassification,
    BoundaryRole,
    BoundaryRoleConfig,
    BoxSelector,
    PlaneSelector,
    classify_boundary_faces,
)
from .constraints import PlaneConstraint, apply_directional_constraints
from .collision import (
    LocalThicknessResult,
    SkinLayerCollisionConfig,
    SkinLayerCollisionError,
    compute_local_thickness_limits,
)
from .core_morph import CoreMorphingConfig, CoreMorphingResult, compute_core_displacement
from .features import (
    EdgeFeature,
    FeatureTopology,
    VertexFeature,
    detect_surface_features,
)
from .offset import OffsetResult, compute_inward_offset
from .generator import (
    SkinLayerConfig,
    SkinLayerQualityConfig,
    SkinLayerQualityError,
    SkinLayerReport,
    SkinLayerResult,
    compute_layer_thicknesses,
    generate_skin_layer,
)
from .generator_2d import (
    BoundaryEdge2D,
    BoundaryTopology2D,
    SkinLayer2DConfig,
    SkinLayer2DQualityConfig,
    SkinLayer2DQualityError,
    SkinLayer2DReport,
    SkinLayer2DResult,
    extract_boundary_edges_2d,
    generate_skin_layer_2d,
)
from .quality import (
    ElementQuality,
    VolumeQualityReport,
    element_qualities,
    evaluate_3d_quality,
    evaluate_element_quality,
    minimum_measure_ratio,
)
from .surface import (
    BoundaryFace,
    SurfaceTopology,
    extract_boundary_surface,
    match_existing_surface_elements,
    validate_surface_topology,
)

__all__ = [
    "BoundaryClassification",
    "BoundaryEdge2D",
    "BoundaryFace",
    "BoundaryRole",
    "BoundaryRoleConfig",
    "BoundaryTopology2D",
    "BoxSelector",
    "CoreMorphingConfig",
    "CoreMorphingResult",
    "EdgeFeature",
    "ElementQuality",
    "FeatureTopology",
    "LocalThicknessResult",
    "OffsetResult",
    "PlaneConstraint",
    "PlaneSelector",
    "SkinLayerConfig",
    "SkinLayer2DConfig",
    "SkinLayer2DQualityConfig",
    "SkinLayer2DQualityError",
    "SkinLayer2DReport",
    "SkinLayer2DResult",
    "SkinLayerCollisionConfig",
    "SkinLayerCollisionError",
    "SkinLayerQualityConfig",
    "SkinLayerQualityError",
    "SkinLayerReport",
    "SkinLayerResult",
    "SurfaceTopology",
    "VertexFeature",
    "VolumeQualityReport",
    "apply_directional_constraints",
    "classify_boundary_faces",
    "compute_inward_offset",
    "compute_local_thickness_limits",
    "compute_layer_thicknesses",
    "compute_core_displacement",
    "detect_surface_features",
    "extract_boundary_surface",
    "extract_boundary_edges_2d",
    "element_qualities",
    "evaluate_3d_quality",
    "evaluate_element_quality",
    "generate_skin_layer",
    "generate_skin_layer_2d",
    "match_existing_surface_elements",
    "minimum_measure_ratio",
    "validate_surface_topology",
]
